{% set version = "1.9.6" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: e0c02b1554b20c710d16d673817b2a89ff94738b0b537aead8ecb2edc4c4487b
  patches:
    - data_dir.patch

build:
  number: 1001
  script:
    - del _proj.c  # [win]
    - rmdir src  # [win]
    - set "PROJ_DIR=%PREFIX%"  # [win]
    - set "PROJ_LIBDIR=%LIBRARY_LIB%"  # [win]
    - set "PROJ_INCDIR=%LIBRARY_INC%"  # [win]
    - rm -d _proj.c  # [not win]
    - rm -rf src
    - export PROJ_DIR="${PREFIX}"  # [not win]
    - export PROJ_LIBDIR="${PREFIX}/lib"  # [not win]
    - export PROJ_INCDIR="${PREFIX}/include"  # [not win]
    - cythonize -a -i _proj.pyx
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4 >=5.2,<6
  run:
    - python
    - numpy
    - proj4 >=5.2,<6

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
